---
collections:
        - community.mongodb
        - name: https://github.com/JavierMS2001/ansible_modules.git
          type: git

        - name: modules.pokeinfo
          source: https://github.com/JavierMS2001/modules.git
          type: git
