---

- name: Install required packages
  apt:
          name: "{{ item  }}"
          state: latest
  loop:
        - php
        - php-gd
        - php-xml
        - php-mbstring
        - php-mysql
  register: "packets"

- name: Restart Apache Service
  become: yes
  service:
          name: apache2
          state: restarted
        
- name: Download Wordpress files
  get_url:
          url: "https://es.wordpress.org/wordpress-6.4.3-es_ES.tar.gz"
          dest: "/tmp/wordpress.tar.gz"

- name: Extract Wordpress files
  unarchive:
          src: "/tmp/wordpress.tar.gz"
          dest: "/var/www/html/"
          remote_src: yes
          owner: www-data
          group: www-data
          mode: '0755'

- name: Enable Wordpress configuration
  template:
          src: files/debian/wp-config.php
          dest: /var/www/html/wordpress/wp-config.php
          owner: www-data
          group: www-data
          mode: '0755'
