---
- name: Install required packages
  apt:
          name: "{{ item  }}"
          state: latest
  loop:
        - php
        - php-gd
        - php-xml
        - php-mbstring
        - php-mysql
  register: "packets"

- name: Restart Apache Service
  become: yes
  service:
          name: apache2
          state: restarted
  when: packets.changed

- name: Check wordpress.tar.gz
  stat:
    path: "/tmp/wordpress.tar.gz"
  register: tar_wordpress

- name: Download Wordpress files
  get_url:
          url: "https://wordpress.org/latest.tar.gz"
          dest: "/tmp/wordpress.tar.gz"
  when: not tar_wordpress.stat.exists

- name: Check wordpress is installing
  stat:
    path: "/var/www/html/wordpress/"
  register: wordpress_file

- name: Extract Wordpress files
  unarchive:
          src: "/tmp/wordpress.tar.gz"
          dest: "/var/www/html/"
          remote_src: yes
          owner: www-data
          group: www-data
          mode: '0755'
            #  when: not wordpress_file.stat.exists
  register: wordpress_installation

- name: Enable Wordpress configuration
  template:
          src: "files/{{ ansible_os_family }}/wp-config.php"
          dest: /var/www/html/wordpress/wp-config.php
          owner: www-data
          group: www-data
          mode: '0755'
  when: wordpress_installation.changed
