---

- name: Establecer la configuración Proxy
  template:
          src: files/proxy.conf
          dest: /etc/httpd/conf.d/proxy.conf
          owner: root
          group: root
          mode: '0644'

- name: Deshabilitar SeLinux
  template:
          src: files/config
          dest: /etc/selinux/config
          owner: root
          group: root
          mode: '0644'
  notify: 
    - "reiniciar servidor"
    - "iniciar httpd"
