---

- name: Establecer la configuración Proxy
  template:
          src: files/proxy.conf
          dest: /etc/httpd/conf.d/proxy.conf
          owner: root
          group: root
          mode: '0644'
