---

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: reboot.yml
  when: reboot in "Y, y, yes"
