---
- name: Crear lista
  set_fact:
    list: "{{ centos_pkgs.split(',') }}"
  when: centos_pkgs | default("null", false)

- name: Instalar dnf
  yum:
    name: dnf
    state: latest
  retries: 3
  delay: 10

- name: Actualizar EPEL Repository
  dnf:
    name: epel-release
    state: latest
  retries: 3
  delay: 10

- name: RedHat - Upgrade all packages, excluding those indicated
  yum:
    name: "*"
    state: latest
    exclude:
      - "{{ list }}*"

- debug:
    msg: "{{ item }} no actualizado."
  with_items: "{{ list }}"
  when: centos_pkgs | default("null", false)
