---

- name: Crear directorio backup
  become: true
  file:
          path: /backup
          state: directory

- name: Buscar archivos en el directorio
  find:
    paths: "{{ backup_dir_centos }}"
    patterns: "*.sql"
    file_type: file
  register: found_files

- name: Ordenar archivos por fecha de modificación
  set_fact:
    sort_files: "{{ found_files.files | sort(attribute='mtime') }}"

- name: Seleccionar el último archivo
  set_fact:
    last_file: "{{ sort_files[-1] }}"
  when: sort_files | length > 1
  register: test

- name: Seleccionar el único archivo
  set_fact:
    last_file: "{{ sort_files[0] }}"
  failed_when: false
  when: not test.changed

  
- name: Copiar el archivo de backup al servidor de base de datos - CentOS
  copy:
    src: "{{ last_file }}"
    dest: "/backup/restore.sql"

- name: Restaurar base de datos
  mysql_db:
      login_user: wordpress-user
      login_password: 1234
      name: bdwordpress
      state: import
      target: /backup/restore.sql
