---
- name: Call to PokeAPI module
  hosts: localhost
  tasks:
    - name: Get Pokemon data
      pokeinfo:
        name: "{{ poke_name }}"
      register: poke_data

    - debug:
        msg:
          - "Name: {{ poke_data.pokemon_data.name }}"
          - "Pokedex ID: {{ poke_data.pokemon_data.id }}"
          - "Type: {{ poke_data.pokemon_data.types }}"
