---
- name: Call to PokeAPI module
  hosts: localhost
  tasks:
    - name: Get Pokemon data
      pokeinfo:
        name: "{{ poke_name }}"
      register: poke_data

    - debug:
        msg:
          - "Name: {{ poke_data.pokemon_data.name }}"
          - "Pokedex ID: {{ poke_data.pokemon_data.id }}"
          - "Type: {% for type in poke_data.pokemon_data.types %}{{ type.type.name }} {% endfor %}"
          - "Base-Stats: {% for stats in poke_data.pokemon_data.stats %} {{ stats.stat.name }}={{ stats.base_stat }}{% endfor %}"
