---
- name: Call to PokeAPI module
  hosts: localhost
  tasks:
    - name: Get Pokemon data
      pokeinfo:
        name: "{{ poke_name }}"
      register: poke_data

    - debug:
        var: poke_data
