---
- name: Build Collection from Git repo
  hosts: localhost
  become: true
  tasks:
    - name: Check if exist repo
      stat:
        path: "/tmp/collections/"
      register: collection_dir

    - name: Remove older repo version
      file:
        path: "/tmp/collections/"
        state: absent
      when: collection_dir is succeeded

    - name: Get Git repo
      git:
        repo: "{{ repo }}"
        dest: "/tmp/collections/"

    - name: Set Module
      copy:
        src: "/tmp/collections/{{ collection_name }}/plugins/modules/{{ module_name }}.py"
        dest: "/var/lib/awx/.ansible/plugins/modules/{{ module_name }}.py"
      when: set_module in "Y, y, yes"

    - name: Build collection 
      shell: "cd /tmp/collections/{{ collection_name }} && ansible-galaxy collection build"

    - name: Install collection
      shell: "cd /tmp/collections/{{ collection_name }} && ansible-galaxy collection install *.tar.gz"
