---
- name: Build Collection from Git repo
  hosts: localhost
  become: true
  tasks:
    - name: Check if exist repo
      stat:
        path: "/tmp/collections/"
      register: collection_dir

    - name: Remove older repo version
      file:
        path: "/tmp/collections/"
        state: absent
      when: collection_dir is succeeded

    - name: Get Git repo
      git:
        repo: "{{ repo }}"
        dest: "/tmp/collections/{{ collection_name }}"

    - name: Build collection 
      shell: "cd /tmp/collections/{{ collection_name }} | ansible-galaxy collection build"

    - name: Install collection
      shell: "cd /tmp/collections/{{ collection_name }} | ansible-galaxy collection install *.tar.gz"

    - name: Remove files
      file:
        path: "/tmp/collections/{{ collection_name }}"
        state: absent
