---
- name: Crear directorio de copias de seguridad
  file:
          path: /backup
          state: directory
          mode: '0755'

- name: Obeneter fecha y hora actual
  set_fact:
          timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"


- name: Realizar backup de la base de datos CentOS
  mysql_db:
          login_user: root
          login_password: vagrant
          state: dump
          name: bdwordpress
          target: "/backup/bdwordpress-CentOS_backup_{{ timestamp }}.sql"

- name: Comprobar si se ha realizado correctamente el backup CentOS
  stat:
          path: "/backup/bdwordpress-CentOS_backup_{{ timestamp }}.sql"
  register: result

- name: Buscar archivos en el directorio
      find:
        paths: "{{ backups_dir }}/CentOS-server/"
        patterns: "*.sql" 
        file_type: file
      register: backups

- name: Ordenar archivos por fecha de modificación
  set_fact:
    order_backups: "{{ backups.files | sort(attribute='mtime') }}"

- name: Eliminar archivos más antiguos si hay más de cinco
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ order_backups | reverse | map(attribute='path') | list }}"
  when: order_backups | length > 5

- name: Importar backup al control node CentOS
  fetch: 
        src: "/backup/bdwordpress-CentOS_backup_{{ timestamp }}.sql"
        #        dest: "/backups/bdwordpress-CentOS/"
        dest: "{{ backups_dir }}/CentOS-server/"
        flat: yes
        when: result is success 
