---
- name: Instalar MariaDB y módulos necesarios - CentOS
  yum:
        name:
                - mariadb-server
                - python3
                - python3-PyMySQL
        state: latest

- name: Reiniciar MariaDB
  service:
          name: mariadb
          enabled: true
          state: restarted

- name: Ejecutar mysql_secure_installation y establecer una contraseña.
  shell: |
          echo -e "\nn\nY\nvagrant\nvagrant\nY\nn\nY\nY\n" | sudo mysql_secure_installation
  args:
   executable: /bin/bash

- name: Crear base de datos para Wordpress
  mysql_db:
          name: bdwordpress
          login_user: root
          login_password: vagrant
          login_host: localhost
          state: present

- name: Crear usuario para la base de datos
  mysql_user:
          name: wordpress-user
          password: 1234
          priv: 'bdwordpress.*:ALL,GRANT'
          host: '%'
          login_user: root
          login_password: vagrant
          login_host: localhost
          state: present

- name: Habilitar el servicio mysql en firewalld CentOS
  firewalld:
          service: mysql
          permanent: true
          state: enabled

- name: Abrir el puerto 3306 en firewalld CentOS
  firewalld:
          port: 3306/tcp
          permanent: true
          state: enabled
  notify: "restart firewall"
