---
- name: Crear lista
  set_fact:
    list: "{{ centos_pkgs.split(',') }}"
  when: centos_pkgs | default("null", false)

- name: Instalar dnf
  yum:
    name: dnf
    state: latest
  retries: 3
  delay: 10

- name: Actualizar EPEL Repository
  dnf:
    name: epel-release
    state: latest
  retries: 3
  delay: 10

- name: Actualizar datos del repositorio
  become: yes
  dnf:
          name: '*'
          update_cache: yes
          exclude:
            - "{{ list }}*"
  retries: 3
  delay: 10

- name: Actualizar paquetes CentOS
  yum:
    name: '*'
    state: latest
    exclude: 
      - "{{ list }}*"
  retries: 3
  delay: 10

- debug:
    msg: "{{ item }} no actualizado."
  with_items: "{{ list }}"
  when: centos_pkgs | default("null", false)
