---

- name: Instalar http
  yum:
          name: httpd
          state: latest
  retries: 3
  delay: 10

- name: Iniciar servicio httpd Debian
  service:
          name: httpd
          state: started


- name: Abrir puerto para el servicio httpd
  firewalld:
          service: http
          permanent: true
          state: enabled
  notify:
          - reiniciar firewalld
          - reiniciar http

