---

- name: Instalar http
  yum:
          name: httpd
          state: latest
  retries: 3
  delay: 10
  notify: "restart http"

- name: Abrir puerto para el servicio httpd
  firewalld:
          service: http
          permanent: true
          state: enabled
  notify: "restart firewalld"

- name: Deshabilitar SeLinux
  template:
          src: files/config
          dest: /etc/selinux/config
          owner: root
          group: root
          mode: '0644'
  notify:
          - "restart server"
          - "restart http"

