---

#- name: Set MongoDB config
#  template:
#          src: files/RedHat/mongod.conf
#          dest: /etc/mongod.conf
#          owner: root
#          group: root
#          mode: '0644'
#  register: restart

#- name: Restart MongoDB service
#  service:
#          name: mongod
#          state: restarted
#  when: restart.changed


- name: Create admin user
  community.mongodb.mongodb_user:
          login_port: "27017"
          database: "admin"
          name: "{{ admin_user }}"
          password: "{{ admin_pass }}"
          roles: "root"

          #- name: Create remote datab
