---

- name: Set MongoDB config
  template:
          src: files/RedHat/mongod.conf
          dest: /etc/mongod.conf
          owner: root
          group: root
          mode: '0644'
  register: restart

- name: Restart MongoDB service
  service:
          name: mongod
          state: restarted
  when: restart.changed

- name: Open port 27017
  firewalld:
          port: 27017/tcp
          permanent: true
          state: enabled
  register: firewall
  ignore_errors: true

- name: Restart firewall
  systemd:
          name: firewalld
          state: restarted
  when: firewall.changed

- name: Open ports to mariadb service with iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 27017
    jump: ACCEPT
  when: firewall.failed

- name: Create RemoteDataBase
  community.mongodb.mongodb_shell:
          login_user: "{{ admin_user }}"
          login_password: "{{ admin_password }}"
          db: "Remotedb"
          eval: "db.createCollection('TestingRemotingDB')"
  when: restart.changed

- name: Create Remote User
  community.mongodb.mongodb_user:
          login_user: "{{ admin_user }}"
          login_password: "{{ admin_password }}"
          database: "Remotedb"
          name: "{{ remote_user }}"
          password: "{{ remote_password }}"
          state: present
          roles:
                  - { db: "admin", role: "readWrite" }
                  - { db: "Remotedb", role: "readWrite" }
  when: restart.changed
