---

- name: Install required packages
  apt:
          name:
                  - gnupg
                  - curl
          state: latest

- name: Import MongoDB key
  become: yes
  apt_key:
          url: "https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc"

- name: Add MongoDB repository to sources.list.d
  become: yes
  lineinfile:
    path: "/etc/apt/sources.list.d/mongodb-org-{{ mongo_version }}.list"
    line: "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/6.0 main"
    create: yes

- name: Update repositories
  become: yes
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
          name: mongodb-org
          state: latest

- name: Start MongoDB Service
  become: yes
  service:
          name: mongod
          state: started
          enabled: yes
