---

- name: Install MongoDB collection
  community.general.collection:
          name: community.mongodb
          state: present
  delegate_to: "localhost"

- name: Install required packages
  apt:
          name:
                  - gnupg
                  - curl
                  - pip
          state: present
  retries: 3
  delay: 10

- name: Import MongoDB key
  become: yes
  apt_key:
          url: "https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc"
  retries: 3
  delay: 10


- name: Add MongoDB repository to sources.list.d
  become: yes
  lineinfile:
    path: "/etc/apt/sources.list.d/mongodb-org-{{ mongo_version }}.list"
    line: "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/6.0 main"
    create: yes
  retries: 3
  delay: 10


- name: Update repositories
  become: yes
  apt:
    update_cache: yes
  retries: 3
  delay: 10


- name: Install MongoDB
  apt:
          name: mongodb-org
          state: latest
  retries: 3
  delay: 10

- name: Install PyMongo
  become: yes
  pip:
          name: pymongo
          state: present
  retries: 3
  delay: 10

- name: Start MongoDB Service
  become: yes
  service:
          name: mongod
          state: started
          enabled: yes
