---

- name: add repo
  become: yes
  yum_repository:
          name: "mongodb-org-{{ rh_mongo_version }}"
          description: 'MongoDB Repository'
          file: mongodb
          baseurl: "https://repo.mongodb.org/yum/redhat/{{ rh_version }}/mongodb-org/{{ rh_mongo_version }}/x86_64/"
          enabled: true
          gpgcheck: true
          gpgkey: "https://www.mongodb.org/static/pgp/server-{{ rh_mongo_version }}.asc"
  retries: 3
  delay: 10

- name: Install MongoDB
  become: yes
  yum:
    name: 
        - mongodb-org
        - mongosh
    state: present
  retries: 3
  delay: 10
  register: installed

- name: Install PyMongo
  become: yes
  pip:
          name: pymongo
          state: present
  retries: 3
  delay: 10

- name: Start MongoDB Service
  become: yes
  service:
          name: mongod
          state: started
          enabled: yes

- name: Create admin user
  community.mongodb.mongodb_user:
          database: admin
          name: "{{ admin_user }}"
          password: "{{ admin_password }}"
          state: present
          roles: ["root"]
  when: installed.changed
