---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "install-{{ ansible_os_family }}.yml"

  #- include_tasks: "config-{{ ansible_os_family }}.yml"
