---

- name: Iniciar MariaDB
  service:
          name: mariadb
          enabled: true
          state: started
  listen: "restart mariadb"

- name: Habilitar UFW
  ufw:
          state: enabled
  listen: "enable ufw"

- name: Recargar configuración del firewall
  ufw:
          state: reloaded
  listen: "reload ufw"
