---
- name: Cleanup
  hosts: localhost
  vars_files:
    - "../../vars/main.yml"
  tasks:

    - name: Remove register file
      file:
        path: "{{ backups_dir }}/register_file.txt"
        state: absent

    - name: Remove mongodb-ubi_molecule-test backups folder
      file:
        path: "{{ backups_dir }}/mongodb-ubi_molecule-test/"
        state: absent

    - name: Remove mongodb-deb_molecule-test backups folder
      file:
        path: "{{ backups_dir }}/mongodb-deb_molecule-test/"
        state: absent
