---
- name: Prepare instances for testing
  hosts: all
  gather_facts: true
  vars_files:
    - "../../vars/main.yml"
  tasks:

  - name: Start MongoDB
    service:
      name: mongod
      enabled: true
      state: started

  - name: Create backup user
    community.mongodb.mongodb_user:
      database: "{{ auth_database }}"
      name: "{{ backup_user }}"
      password: "{{ user_password }}"
      state: present
      roles: ["root"]

  - name: Create database to test backup rol
    community.mongodb.mongodb_shell:
      login_user: "{{ backup_user }}"
      login_password: "{{ user_password }}"
      db: "{{ database_name }}"
      eval: "db.createCollection('BackupTestingDB')"
