- name: Verify
  hosts: all
  vars_files:
    - "../../vars/main.yml"
  tasks:
    - name: Read register file
      shell: "cat {{ backups_dir }}/register_file.txt"
      register: register_file_content
      delegate_to: localhost

    - name: Verify backup file
      stat:
        path: "{{ register_file_content.stdout }}"
      register: register_file_stat
      delegate_to: localhost
      failed_when: not register_file_stat.stat.exists

    - name: Backup is working
      debug:
        msg: "Backup working correctly!"
      when: register_file_stat.stat.exists
