---
- name: Prepare instances for testing
  hosts: all
  gather_facts: true
  vars_files:
    - "../../vars/main.yml"
  tasks:

  - name: Start MariaDB
    service:
      name: mariadb
      enabled: true
      state: started

  - name: Set root password to ubi
    shell: |
          echo -e "\nn\nY\n{{ db_password }}\n{{ db_password }}\nY\nn\nY\nY\n" | sudo mariadb-secure-installation
    args:
      executable: /bin/bash
    when: ansible_os_family == "RedHat"
   
  - name: Create database to test backup rol
    mysql_db:
      name: "{{ db_name }}"
      login_user: root
      login_password: "{{ db_password }}"
      login_host: localhost
      state: present
