---

- name: Obtener la lista de backups de CentOS
  find:
          paths: "{{ backups_dir }}/CentOS-server/"
          patterns: "*.sql"
          file_type: file
  register: centos_sql_files
  delegate_to: localhost

- name: Debug latest_centos_sql_file
  debug:
    var: centos_sql_files

- name: Ordenar backups CentOS
  set_fact:
          sorted_centos_sql_files: "{{ centos_sql_files.files | sort(attribute='mtime') | reverse }}"

- name: Seleccionar ultima backup modificada CentOS
  set_fact:
          latest_centos_sql_file: "{{ sorted_centos_sql_files[0] }}"

- name: Debug latest_centos_sql_file
  debug:
    var: latest_centos_sql_file

- name: Crear directorio backup
  become: true
  file:
          path: /backup
          state: directory

- name: Copiar backup a servidor remoto CentOS
  copy: 
          content: "{{ lookup('file', latest_centos_sql_file.path) }}"
          dest: /backup/restore.sql

- name: Restaurar base de datos
  mysql_db:
          login_user: wordpress-user
          login_password: 1234
          name: bdwordpress
          state: import
          target: /backup/restore.sql
