---

- name: Create /backup directory
  become: true
  file:
          path: /backup
          state: directory

- name: Search backups files in /backup
  find:
    paths: "{{ backup_dir_centos }}"
    patterns: "*.sql"
    file_type: file
  register: found_files
  delegate_to: "{{ backup_server }}"

- name: Select last backup file
  set_fact:
    last_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
  delegate_to: "{{ backup_server }}"
  
- name: Copy backup file to database server - CentOS
  copy:
    src: "{{ last_file.path }}"
    dest: "/backup/restore.sql"

- name: Rescovery backup
  mysql_db:
      login_user: "{{ db_username }}"
      login_password: "{{ db_password }}"
      name: "{{ db_name }}"
      state: import
      target: /backup/restore.sql
