---

- name: Check backup directory
  become: true
  file:
          path: /backup
          state: directory

- name: Search backup files in directory
  find:
    paths: "{{ backup_dir_debian }}"
    patterns: "*.sql"
    file_type: file
  register: found_files
  delegate_to: "{{ backup_server }}"

- name: Select last backup file
  set_fact:
    last_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
  delegate_to: "{{ backup_server }}"
  
- name: Copy backup file to database server - Debian
  copy:
    src: "{{ last_file.path }}"
    dest: "/backup/restore.sql"

- name: Recovery database
  mysql_db:
      login_user: "{{ db_username }}"
      login_password: "{{ db_password }}"
      name: "{{ db_name }}"
      state: import
      target: /backup/restore.sql
