---
- name: Prepare instances for testing
  hosts: mongodb-deb_molecule-test, mongodb-ubi_molecule-test
  gather_facts: true
  tasks:

  - name: Debian - Update cache
    apt:
      update_cache: yes
    retries: 3
    delay: 10
    when: ansible_os_family == "Debian"

  - name: Install iptables - RedHat
    yum:
      name: iptables
      state: present
    when: ansible_os_family == "RedHat"
