---

- name: Reiniciar servidor remoto
  reboot:
          reboot_timeout: 30
          post_reboot_delay: 30
  listen: "restart server"

- name: Iniciar servicio httpd
  service:
          name: httpd
          state: started
  listen: "start httpd"

- name: Reiniciar servicio httpd
  service:
          name: httpd
          state: restarted
  listen: "restart httpd"
