---

- name: Reiniciar servidor remoto
  reboot:
          reboot_timeout: 30
          post_reboot_delay: 30
  listen: "reiniciar servidor"

- name: Iniciar servicio httpd
  service:
          name: httpd
          state: started
  listen: "iniciar httpd"
