---
- name: Create backup dir
  file:
          path: /backups
          state: directory
          mode: '0755'

- name: Get actual time and date
  set_fact:
          timestamp: "{{ ansible_date_time.date }}"

- name: Dump the database
  command: >
          sudo mongodump 
          -u "{{ backup_user }}" 
          -p "{{ user_password }}" 
          --authenticationDatabase "{{ auth_database }}" 
          --db "{{ database_name }}" 
          --archive="/backups/MongoDB/TestBackup_{{ database_name }}-{{ timestamp }}.tar.gz"

- name: Check backup
  stat:
          path: "/backups/MongoDB/{{ database_name }}_backup-{{ timestamp }}.tar.gz"
  register: result

- name: Import backup to control node
  fetch:
          src: "/backups/MongoDB/{{ database_name }}_backup-{{ timestamp }}.tar.gz"
          dest: "{{ backups_dir }}/{{ ansible_distribution }}/"
          flat: yes
          when: result is success
