---
- name: Create backup dir
  file:
          path: /backup/MongoDB/
          state: directory
          mode: '0755'

- name: Get actual time and date
  set_fact:
          timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"

- name: Dump the database
  command: >
          sudo mongodump 
          -u "{{ backup_user }}" 
          -p "{{ user_password }}" 
          --authenticationDatabase "{{ auth_database }}" 
          --db "{{ database_name }}" 
          --archive="/backup/MongoDB/TestBackup_{{ database_name }}-{{ timestamp }}.tar.gz"

- name: Check backup
  stat:
          path: "{{ backup_path }}"
  register: result

- name: Import backup to control node
  fetch:
          src: "{{ backup_path }}"
          dest: "{{ backups_dir }}/{{ ansible_distribution }}/"
          flat: yes
          when: result is success
