---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  gather_facts: true
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"

  roles:
    - role: install-apache
