---
- name: Prepare instances for testing
  hosts: all
  gather_facts: true
  tasks:
    - name: Install iptables - RedHat
      yum:
        name: iptables
        state: present
      when: ansible_os_family == "RedHat"
