---
- name: Verify
  hosts: all
  tasks:

  - name: Testing apache is running
    uri:
      url: http://localhost/
      method: GET
      status_code: 200
      return_content: yes
    register: test
    failed_when: test.status != 200
    
  - name: Apache is working!
    debug:
      msg: "Apache is working in {{ ansible_host }}!"
    when: test.status == 200
