---
- name: Install MariaDB and others necessary modules
  yum:
        name:
                - mariadb-server
                - python3
                - python3-PyMySQL
        state: latest
  register: install

- name: Restart MariaDB
  service:
          name: mariadb
          enabled: true
          state: restarted
  when: install.changed

- name: Use mysql_secure_installation to set password.
  shell: |
          echo -e "\nn\nY\n{{ db_root_pass }}\n{{ db_root_pass }}\nY\nn\nY\nY\n" | sudo mariadb-secure-installation
  args:
   executable: /bin/bash
  when: install.changed

- name: Create database
  mysql_db:
          name: "{{ database_name }}"
          login_user: "{{ db_root_user }}"
          login_password: "{{ db_root_pass }}"
          login_host: localhost
          state: present

- name: Create user to database
  mysql_user:
          name: "{{ db_username }}"
          password: "{{ db_user_pass }}"
          priv: 'bdwordpress.*:ALL,GRANT'
          host: '%'
          login_user: "{{ db_root_user }}"
          login_password: "{{ db_root_pass }}"
          login_host: localhost
          state: present

- name: Enable mysql service in firewall
  firewalld:
          service: mysql
          permanent: true
          state: enabled
  register: firewall
  ignore_errors: true

- name: Open port 3306
  firewalld:
          port: 3306/tcp
          permanent: true
          state: enabled
  when: firewall.changed

- name: Restart firewall
  systemd:
          name: firewalld
          state: restarted
  when: firewall.changed

- name: Open ports to mariadb service with iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    jump: ACCEPT
  when: firewall.failed

