---

- name: Install http
  yum:
          name: httpd
          state: latest
  retries: 3
  delay: 10

- name: Start Apache
  service:
          name: httpd
          state: started
          enabled: yes

- name: Open ports to HTTPD service with firewalld
  firewalld:
          service: http
          permanent: true
          state: enabled
  register: result
  ignore_errors: true

- name: Reload Firewall
  service:
          name: firewalld
          state: reloaded
  when: result is succeeded

- name: Open ports to HTTPD service with iptables
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
  when: result is failed

- name: Desactivate SeLinux
  template:
          src: files/config
          dest: /etc/selinux/config
          owner: root
          group: root
          mode: '0644'
  register: reboot
  when: selinux in "Y, y, yes"

- name: Reboot server
  reboot:
          reboot_timeout: 30
          post_reboot_delay: 30
  when: reboot.changed

- name: Start Apache
  service:
          name: httpd
          state: started
          enabled: yes
  when: reboot.changed
