---

- name: Crear directorio de copias de seguridad
  file:
          path: /backup
          state: directory
          mode: '0755'

- name: Obeneter fecha y hora actual
  set_fact:
          timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

- name: Realizar backup de la base de datos Debian
  mysql_db:
          state: dump
          name: bdwordpress
          target: "/backup/bdwordpress-Debian_backup_{{ timestamp }}.sql"

- name: Comprobar si se ha realizado correctamente el backup Debian
  stat:
          path: "/backup/bdwordpress-Debian_backup_{{ timestamp }}.sql"
  register: result

- name: Importar backup al control node Debian
  fetch:
        src: "/backup/bdwordpress-Debian_backup_{{ timestamp }}.sql"
        #        dest: "/bachup/bdwordpress-Debian/"
        dest: "{{ backups_dir }}/bdwordpress-Debian/"
        flat: yes
        when: result is success
