---
- name: Instalar MariaDB
  hosts: mariadb
  become: true

  roles:
    - role: mariadb_centos
      when: ansible_distribution == 'CentOS'

    - role: mariadb_debian
      when: ansible_distribution == 'Debian'
