---
- name: Ejecutar el comando df
  command: df -h
  register: df_output

- name: Mostrar resultado del comando df
  debug:
    msg: "{{ df_output.stdout | to_nice_json | regex_replace('\\\\n', '\\n') | from_json | to_nice_yaml }}"
