---
- name: Ejecutar el comando df
    shell: |
            df -h | awk 'NR==1 || !/^Filesystem/ {print}'
  register: df_output

- name: Mostrar resultado del comando df
  debug:
    msg: "{{ df_output.stdout }}"
