---
- name: Instalar Apache
  hosts: apache,wordpress
  become: true

  roles:
    - role: apache_centos
      when: ansible_distribution == 'CentOS'

    - role: apache_debian
      when: ansible_distribution == 'Debian'
