---

- name: Instalar paquetes requeridos
  apt:
          name: "{{ item  }}"
          state: latest
  loop:
        - php
        - php-gd
        - php-xml
        - php-mbstring
        - php-mysql
  notify: "restart apache"
- name: Descargar archivo de WordPress Debian
  get_url:
          url: "https://wordpress.org/latest.tar.gz"
          dest: "/tmp/wordpress.tar.gz"

- name: Extraer archivo de WordPress Debian
  unarchive:
          src: "/tmp/wordpress.tar.gz"
          dest: "/var/www/html/"
          remote_src: yes
          owner: www-data
          group: www-data
          mode: '0755'

- name: Establecer configuración WordPress Debian
  template:
          src: files/wp-config.php
          dest: /var/www/html/wordpress/wp-config.php
          owner: www-data
          group: www-data
          mode: '0755'
