---

- name: Reiniciar MariaDB
  service:
          name: mariadb
          enabled: true
          state: started
  listen: "restart mariadb"

- name: Reiniciar firewall
  systemd:
          name: firewalld
          state: restarted
  listen: "restart firewall"
