---

- name: Reiniciar firewall
  ufw:
          state: reloaded
  listen: "restart firewall"

- name: Reiniciar servicio apache
  become: yes
  service:
          name: apache2
          state: restarted
  listen: "restart apache"
